#!/bin/bash
'''
if ! command -v socat
then
    clear
    echo "Instalando socat"
    sudo apt update
    sudo apt install -y socat
fi
if ! command -v xclip
then
    clear
    echo "Instalando xclip"
    sudo apt update
    sudo apt install -y xclip
fi
'''
clear
PASTA_DO_CONDOR=$(pwd)
PREFIXO_DO_WINE="$PASTA_DO_CONDOR/wineprefix"
#PREFIXO_DO_WINE="$HOME/.wine32"
echo "Configurando XCSoar"
WINEPREFIX=$PREFIXO_DO_WINE ./wine.AppImage regedit /s $PASTA_DO_CONDOR/SerialComm.reg
echo "111-YHL0-53NI" | xclip -selection clipboard
WINEPREFIX=$PREFIXO_DO_WINE ./wine.AppImage regedit /s $PASTA_DO_CONDOR/SerialComm.reg
socat PTY,link=$PREFIXO_DO_WINE/dosdevices/com6 PTY,link=$PREFIXO_DO_WINE/dosdevices/com7&WINEPREFIX=$PREFIXO_DO_WINE ./wine.AppImage $PASTA_DO_CONDOR/Condor.exe&WINEPREFIX=$PREFIXO_DO_WINE ./wine.AppImage $PASTA_DO_CONDOR/XCSoar.exe
#socat PTY,link=$PREFIXO_DO_WINE/dosdevices/com6 PTY,link=$PREFIXO_DO_WINE/dosdevices/com7&./wine.AppImage $PASTA_DO_CONDOR/Condor.exe&./wine.AppImage $PASTA_DO_CONDOR/XCSoar.exe
rm -rf $PREFIXO_DO_WINE
